version: "3.7"
services:
  app:
    build:
      context: .
    expose:
      - 8080
    networks:
      - yaco_net

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "8080:8080"

networks:
  yaco_net:
    driver: bridge
    name: yaco_net