version: "3.7"
services:
  app:
    container_name: yaco_fashion
    build:
      context: .
    env_file:
      - .env
    expose:
      - 8080
    networks:
      - yaco_net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: on-failure
    networks:
      - yaco_net

networks:
  yaco_net:
    driver: bridge
    name: yaco_net