version: "3.7"
services:
  app:
    container_name: yaco_fashion
    build:
      context: .
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
    env_file:
      - .env
    expose:
      - 8080
    networks:
      - yaco_net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: on-failure
    networks:
      - yaco_net

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot

networks:
  yaco_net:
    driver: bridge
    name: yaco_net