spring:
  config:
    active:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

opensearch_domain_name: yaco-search

dictionary:
  s3_bucket_name: yaco-es-dictionary
  words:
    s3_key: prod/words.txt
    package_name: words
  synonyms:
    s3_key: prod/synonyms.txt
    package_name: synonyms