spring:
  config:
    active:
      on-profile: common
  datasource:
    url: jdbc:mariadb://${YACO_DB_HOST}:3306/${YACO_DB_NAME}?useUnicode=yes&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${YACO_DB_USER}
    password: ${YACO_DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      jdbc:
        time_zone: KST
      hibernate:
        format_sql: true
        use_sql_comments: false

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

elasticsearch:
  host: ${YACO_ES_HOST}
  port: ${YACO_ES_PORT}
  index:
    goods: goods