spring:
  config:
    active:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${YACO_DB_HOST}:3306/${YACO_DB_NAME}?useUnicode=yes&serverTimezone=Asia/Seoul&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

dictionary:
  s3_bucket_name: yaco-es-dictionary
  words:
    s3_prefix: prod
  synonyms:
    s3_prefix: prod