spring:
  config:
    active:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

elasticsearch:
  host: ${YACO_ES_PROXY_HOST}
  port: ${YACO_ES_PROXY_PORT}